<?php
include("class/lib/class.ObjectSQL.php");

$ms_db = mssql_connect("GM-30","jramos","A123456a");
mssql_select_db("SERVICIOSM",$ms_db);


//$obj= new ObjectSQL();
//$SQL=$obj->getSQL("insert","sys_personas");

agregar_nuevos_clientes($ms_db,"01-07-2013","31-07-2013");
//insertar_nuevo_cierre_clientes($ms_db);



function insertar_nuevo_cierre_clientes($ms_db){
 $SQL="SELECT 
    dbo.TABLA_AUDITORES.CONTRATO
  FROM
    dbo.TABLA_AUDITORES WHERE
  ESTADO<>'Desistido'";
	$rs=mssql_query($SQL,$ms_db);
	while($row=mssql_fetch_assoc($rs)){
		$sp=explode(" ",$row['CONTRATO']);
		
		$data=optener_datos_clientes($ms_db,$sp[0],$sp[1]);
	
		if (count($data)>0){
			if ($data['CONTRATO']!=NULL){
				$obj= new ObjectSQL();
				$data['PLAN_FINAN']= trim($data['PLAN_FINAN']);
				$data['CAP_VENC_CUOTAS']= $data['CAP_VENC_CUOTAS']!=NULL?$data['CAP_VENC_CUOTAS']:0;
				$data['TOTAL_VENCIDO']= $data['TOTAL_VENCIDO']!=NULL?$data['TOTAL_VENCIDO']:0;
				$data['INT_VENC_CUOTAS']= $data['INT_VENC_CUOTAS']!=NULL?$data['INT_VENC_CUOTAS']:0;
				$data['SERVICIOS']=0;
				$data['MES']="datepart(month,getdate())";
				$data['ANO']="datepart(year,getdate())";
				$data['PRECIO']="convert(float,'".$data['PRECIO']."')";
				$data['INICIAL']="convert(float,'".$data['INICIAL']."')";
				$data['TOTAL_CUOTAS']="convert(float,'".$data['TOTAL_CUOTAS']."')";
			//	$data['FECHA_PRIMER_PAGO']="convert(float,'".$data['FECHA_PRIMER_PAGO']."')";
				$data['MONTO_CUOTA']="convert(float,'".$data['MONTO_CUOTA']."')";
				$data['NRO_CUOTAS_CANC']="convert(float,'".$data['NRO_CUOTAS_CANC']."')";
				$data['CAP_CANC_CUOTAS']="convert(float,'".$data['CAP_CANC_CUOTAS']."')";
				$data['INT_CANC_CUOTAS']="convert(float,'".$data['INT_CANC_CUOTAS']."')";
				$data['TOTAL_CANCELADO']="convert(float,'".$data['TOTAL_CANCELADO']."')";
				$data['NRO_CUOTAS_VENC']="convert(float,'".$data['NRO_CUOTAS_VENC']."')";
				$data['CAP_VENC_CUOTAS']="convert(float,'".$data['CAP_VENC_CUOTAS']."')";
				$data['INT_VENC_CUOTAS']="convert(float,'".$data['INT_VENC_CUOTAS']."')";
				$data['TOTAL_VENCIDO']="convert(float,'".$data['TOTAL_VENCIDO']."')";
				$data['CAPITAL_PEND']="convert(float,'".$data['CAPITAL_PEND']."')";
				$data['INTERES_PEND']="convert(float,'".$data['INTERES_PEND']."')";
				$data['TOTAL_PENDIENTE']="convert(float,'".$data['TOTAL_PENDIENTE']."')";
				$data['SERVICIOS']="convert(float,'".$data['SERVICIOS']."')";
				$data['FECHA_VENTA']="convert(int,'".$data['FECHA_VENTA']."')";
				$data['FECHA_PRIMER_PAGO']="convert(int,'".$data['FECHA_PRIMER_PAGO']."')";
		
				print_r($data);
		
				$obj->phush_obj($data);
				$SQL=$obj->getSQL("insert","TABLA_AUDITORES");
				//mssql_query($SQL);
			}
		}
		//echo $SQL;
	//	exit;
		//sleep(2);
	//	exit;
	}

}

function agregar_nuevos_clientes($ms_db,$date_from="01-06-2013",$date_to="30-06-2013"){


$SQL="SELECT 
		  PRO_CONTRATOS.CTT_COD_CLIENTE,
		(PRO_CONTRATOS.CTT_COD_TD +' '+PRO_CONTRATOS.CTT_CODIGO) as contrato,
		PRO_CONTRATOS.CTT_COD_TD,
		PRO_CONTRATOS.CTT_CODIGO
		FROM
		  PRO_CONTRATOS
		WHERE
		  CTT_ANULADO = 0 AND 
		  CTT_RECIBO = 0 AND 
		  PRO_CONTRATOS.CTT_COD_TD='CM' AND
		  
		(PRO_CONTRATOS.CTT_COD_TD +' '+PRO_CONTRATOS.CTT_CODIGO)   NOT in (SELECT 
		  dbo.TABLA_AUDITORES.CONTRATO
		FROM
		  dbo.TABLA_AUDITORES WHERE
		ESTADO<>'Desistido') AND
  CONVERT(DATETIME,PRO_CONTRATOS.CTT_FECHA,103)
   BETWEEN CONVERT(DATETIME,convert(VARCHAR, '".$date_from."', 103),103) AND 
   CONVERT(DATETIME,convert(VARCHAR, '".$date_to."', 103),103)	
		
		";
				
	$rs=mssql_query($SQL,$ms_db);
	while($row=mssql_fetch_assoc($rs)){
		
		$data=optener_datos_clientes($ms_db,$row['CTT_COD_TD'],$row['CTT_CODIGO']);
	
		if (count($data)>0){
			if ($data['CONTRATO']!=NULL){
				$obj= new ObjectSQL();
				$data['PLAN_FINAN']= trim($data['PLAN_FINAN']);
				$data['CAP_VENC_CUOTAS']= $data['CAP_VENC_CUOTAS']!=NULL?$data['CAP_VENC_CUOTAS']:0;
				$data['TOTAL_VENCIDO']= $data['TOTAL_VENCIDO']!=NULL?$data['TOTAL_VENCIDO']:0;
				$data['INT_VENC_CUOTAS']= $data['INT_VENC_CUOTAS']!=NULL?$data['INT_VENC_CUOTAS']:0;
				$data['SERVICIOS']=0;
				$data['MES']="datepart(month,getdate())";
				$data['ANO']="datepart(year,getdate())";
				$data['PRECIO']="convert(float,'".$data['PRECIO']."')";
				$data['INICIAL']="convert(float,'".$data['INICIAL']."')";
				$data['TOTAL_CUOTAS']="convert(float,'".$data['TOTAL_CUOTAS']."')";
			//	$data['FECHA_PRIMER_PAGO']="convert(float,'".$data['FECHA_PRIMER_PAGO']."')";
				$data['MONTO_CUOTA']="convert(float,'".$data['MONTO_CUOTA']."')";
				$data['NRO_CUOTAS_CANC']="convert(float,'".$data['NRO_CUOTAS_CANC']."')";
				$data['CAP_CANC_CUOTAS']="convert(float,'".$data['CAP_CANC_CUOTAS']."')";
				$data['INT_CANC_CUOTAS']="convert(float,'".$data['INT_CANC_CUOTAS']."')";
				$data['TOTAL_CANCELADO']="convert(float,'".$data['TOTAL_CANCELADO']."')";
				$data['NRO_CUOTAS_VENC']="convert(float,'".$data['NRO_CUOTAS_VENC']."')";
				$data['CAP_VENC_CUOTAS']="convert(float,'".$data['CAP_VENC_CUOTAS']."')";
				$data['INT_VENC_CUOTAS']="convert(float,'".$data['INT_VENC_CUOTAS']."')";
				$data['TOTAL_VENCIDO']="convert(float,'".$data['TOTAL_VENCIDO']."')";
				$data['CAPITAL_PEND']="convert(float,'".$data['CAPITAL_PEND']."')";
				$data['INTERES_PEND']="convert(float,'".$data['INTERES_PEND']."')";
				$data['TOTAL_PENDIENTE']="convert(float,'".$data['TOTAL_PENDIENTE']."')";
				$data['SERVICIOS']="convert(float,'".$data['SERVICIOS']."')";
				$data['FECHA_VENTA']="convert(int,'".$data['FECHA_VENTA']."')";
				$data['FECHA_PRIMER_PAGO']="convert(int,'".$data['FECHA_PRIMER_PAGO']."')";
		
				print_r($data);
		
				$obj->phush_obj($data);
				$SQL=$obj->getSQL("insert","TABLA_AUDITORES");
				mssql_query($SQL);
			}
		}
		//echo $SQL;
	//	exit;
		//sleep(2);
	//	exit;
	}
}


function optener_datos_clientes($ms_db,$cod_dt="CM",$codigo="00624"){
	
	$SQL="SELECT 
  BAS_ESTADO_CONTRATO.ESC_DESCRIPCION AS ESTADO,
  PRO_PLANES_VENTA.PLN_DESCRIPCION AS PLAN_FINAN,
  BAS_MONEDAS.MON_DESCRIPCION AS MONEDA,
  CONTRATOS_CCT.CTT_INICIAL AS INICIAL,
  CONTRATOS_CCT.CTT_PLAZO AS TOTAL_CUOTAS,
  CONTRATOS_CCT.CTT_MONTO_CUOTA AS MONTO_CUOTA,
  CONTRATOS_CCT.CTT_COD_TD +' '+CONTRATOS_CCT.CTT_CODIGO AS CONTRATO,
  CLI_DESCRIPCION AS NOMBRE_CLIENTE,
  cast(cast(CONTRATOS_CCT.CTT_FECHA as float) as int)
  AS FECHA_VENTA,

(SELECT 
	max(PRO_CONTRATOS_DEUDAS.DEU_NRO_CUOTA) as NO_CUOTAS
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0   AND 
  VTA_TIPO_DOC_APLICA = DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC') 
  as NRO_CUOTAS_CANC,
  (SELECT 
   MAX(PRO_CONTRATOS.CTT_INICIAL) + sum(DEU_MONTO) as MONTO_CANCELADO
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0   AND 
  VTA_TIPO_DOC_APLICA =DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC') +
  ( SELECT 
    sum(DEU_MONTO) as MONTO_PENDIENTE 
 FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL )
   as PRECIO,
 (SELECT 
  cast(cast(PRO_CONTRATOS_DEUDAS.DEU_FECHA_CANC as float) as int) as DEU_FECHA_CANC
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0 AND 
  VTA_TIPO_DOC_APLICA = DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC' and
  PRO_CONTRATOS_DEUDAS.DEU_NRO_CUOTA=1)  
  as FECHA_PRIMER_PAGO,
  (SELECT 
   sum(DEU_MONTO) as CAP_CANC_CUOTAS
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND  
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0   AND 
  VTA_TIPO_DOC_APLICA =DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC') 
  as CAP_CANC_CUOTAS,
(SELECT 
  sum(DEU_INTERES_FINANCIAMIENTO) AS  INT_CANC_CUOTAS 
  FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0   AND 
  VTA_TIPO_DOC_APLICA =DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC') 
  AS INT_CANC_CUOTAS,
  
  ((SELECT 
   sum(DEU_MONTO) as CAP_CANC_CUOTAS
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND  
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0   AND 
  VTA_TIPO_DOC_APLICA =DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC') 
+(SELECT 
  sum(DEU_INTERES_FINANCIAMIENTO) AS  INT_CANC_CUOTAS 
  FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA,
  MAE_CC_VENTAS
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  VTA_ANULADO = 0   AND 
  VTA_TIPO_DOC_APLICA =DEU_COD_TIPO_DOCUMENTO AND 
  VTA_NRO_DOC_APLICA = PRO_CONTRATOS_DEUDAS.DEU_NUMERO AND 
  VTA_COD_TIPO_DOCUMENTO <> 'AC')) 
  AS TOTAL_CANCELADO,
  
  (SELECT 
  COUNT(PRO_CONTRATOS_DEUDAS.DEU_FECHA_VENCE) AS TOTAL
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL AND
  PRO_CONTRATOS_DEUDAS.DEU_FECHA_VENCE<GETDATE()) 
  AS NRO_CUOTAS_VENC,
(SELECT 
	sum(DEU_MONTO) as MONTO_PENDIENTE
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL AND
  PRO_CONTRATOS_DEUDAS.DEU_FECHA_VENCE<GETDATE())
  AS CAP_VENC_CUOTAS,
 
(SELECT 
	sum(DEU_INTERES_FINANCIAMIENTO)+sum(DEU_INTERES_FINANCIAMIENTO_2) as INT_VENC_CUOTAS	

FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL AND
  PRO_CONTRATOS_DEUDAS.DEU_FECHA_VENCE<GETDATE())
  as  INT_VENC_CUOTAS,
 
((SELECT 
	sum(DEU_MONTO) as MONTO_PENDIENTE
FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL AND
  PRO_CONTRATOS_DEUDAS.DEU_FECHA_VENCE<GETDATE())
+
(SELECT 
	sum(DEU_INTERES_FINANCIAMIENTO)+sum(DEU_INTERES_FINANCIAMIENTO_2) as INT_VENC_CUOTAS	

FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND 
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL AND
  PRO_CONTRATOS_DEUDAS.DEU_FECHA_VENCE<GETDATE())
  )
  as   TOTAL_VENCIDO,
  
  (SELECT 
    sum(DEU_MONTO) as  CAPITAL_PEND  
 FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL ) 
  AS  CAPITAL_PEND ,
  
  (SELECT 
	sum(DEU_INTERES_FINANCIAMIENTO)+sum(DEU_INTERES_FINANCIAMIENTO_2) as  INTERES_PEND 
 FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL ) 
  AS INTERES_PEND,

(  (SELECT 
    sum(DEU_MONTO) as  CAPITAL_PEND  
 FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL ) 
  +
  
  (SELECT 
	sum(DEU_INTERES_FINANCIAMIENTO)+sum(DEU_INTERES_FINANCIAMIENTO_2) as  INTERES_PEND 
 FROM
  PRO_CONTRATOS_DEUDAS,
  PRO_CONTRATOS,
  MAE_CC_CLIENTES,
  MAE_MATERIALES,
  PRO_PLANES_VENTA
WHERE
  CTT_COD_TD = DEU_COD_TD AND 
  CTT_CODIGO = DEU_COD_CONTRATO AND 
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  PRO_CODIGO = DEU_COD_SERVICIO AND
  CLI_CODIGO = CLIENTES_CC.CLI_CODIGO AND 
  CTT_COD_TD = CONTRATOS_CCT.CTT_COD_TD AND 
  CTT_CODIGO = CONTRATOS_CCT.CTT_CODIGO AND 
  CTT_RECIBO = 0 AND 
  PLN_COD_SERVICIO = DEU_COD_SERVICIO AND 
  DEU_REFINANCIADA = 0 AND 
  PRO_CONTRATOS_DEUDAS.DEU_NUMERO IS NULL ) )
  AS  TOTAL_PENDIENTE

FROM
  BAS_ESTADO_CONTRATO,
  PRO_PLANES_VENTA,
  BAS_MONEDAS,
  PRO_CONTRATOS AS CONTRATOS_CCT,
  MAE_CC_CLIENTES AS CLIENTES_CC
WHERE
  CLI_CODIGO = CTT_COD_CLIENTE AND 
  ESC_CODIGO = CTT_COD_ESTADO AND 
  PLN_CODIGO = CTT_COD_PLAN AND 
  MON_CODIGO = CTT_COD_MONEDA AND 
  CTT_CODIGO = '".$codigo."' AND 
  CTT_COD_TD = '". $cod_dt ."'";
  
  //echo $codigo." ".$cod_dt;
	$rs=@mssql_query($SQL,$ms_db);
	if ($rs!=null){
		while($row=mssql_fetch_assoc($rs)){
			return $row;
		}
	}
}



?>